// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UnifiedServiceScheduler.Data;

#nullable disable

namespace UnifiedServiceScheduler.Migrations
{
    [DbContext(typeof(ServiceSchedulerDbContext))]
    partial class ServiceSchedulerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UnifiedServiceScheduler.Data.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("DealershipId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServiceBayId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleVin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("ServiceBayId", "StartTime", "EndTime")
                        .HasDatabaseName("IX_Appointment_ServiceBay_TimeSlot");

                    b.HasIndex("TechnicianId", "StartTime", "EndTime")
                        .HasDatabaseName("IX_Appointment_Technician_TimeSlot");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("UnifiedServiceScheduler.Data.Entities.ServiceBay", b =>
                {
                    b.Property<int>("ServiceBayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceBayId"));

                    b.Property<string>("BayNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DealershipId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("ServiceBayId");

                    b.HasIndex("DealershipId", "BayNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ServiceBay_Dealership_BayNumber_Unique");

                    b.ToTable("ServiceBays");

                    b.HasData(
                        new
                        {
                            ServiceBayId = 1,
                            BayNumber = "BAY-001",
                            DealershipId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ServiceBayId = 2,
                            BayNumber = "BAY-002",
                            DealershipId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ServiceBayId = 3,
                            BayNumber = "BAY-003",
                            DealershipId = 1,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("UnifiedServiceScheduler.Data.Entities.ServiceType", b =>
                {
                    b.Property<int>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceTypeId"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ServiceTypeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_ServiceType_Name_Unique");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            ServiceTypeId = 1,
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            Name = "Oil Change"
                        },
                        new
                        {
                            ServiceTypeId = 2,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            Name = "Brake Repair"
                        },
                        new
                        {
                            ServiceTypeId = 3,
                            Duration = new TimeSpan(0, 0, 45, 0, 0),
                            Name = "Tire Rotation"
                        },
                        new
                        {
                            ServiceTypeId = 4,
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            Name = "Engine Diagnostic"
                        },
                        new
                        {
                            ServiceTypeId = 5,
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Name = "Transmission Service"
                        });
                });

            modelBuilder.Entity("UnifiedServiceScheduler.Data.Entities.Technician", b =>
                {
                    b.Property<int>("TechnicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TechnicianId"));

                    b.Property<int>("DealershipId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TechnicianId");

                    b.HasIndex("DealershipId")
                        .HasDatabaseName("IX_Technician_DealershipId");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            TechnicianId = 1,
                            DealershipId = 1,
                            IsActive = true,
                            Name = "John Smith"
                        },
                        new
                        {
                            TechnicianId = 2,
                            DealershipId = 1,
                            IsActive = true,
                            Name = "Sarah Johnson"
                        },
                        new
                        {
                            TechnicianId = 3,
                            DealershipId = 1,
                            IsActive = true,
                            Name = "Mike Wilson"
                        });
                });

            modelBuilder.Entity("UnifiedServiceScheduler.Data.Entities.TechnicianQualification", b =>
                {
                    b.Property<int>("TechnicianId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer");

                    b.HasKey("TechnicianId", "ServiceTypeId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("TechnicianQualifications");

                    b.HasData(
                        new
                        {
                            TechnicianId = 1,
                            ServiceTypeId = 1
                        },
                        new
                        {
                            TechnicianId = 1,
                            ServiceTypeId = 3
                        },
                        new
                        {
                            TechnicianId = 2,
                            ServiceTypeId = 2
                        },
                        new
                        {
                            TechnicianId = 2,
                            ServiceTypeId = 4
                        },
                        new
                        {
                            TechnicianId = 3,
                            ServiceTypeId = 1
                        },
                        new
                        {
                            TechnicianId = 3,
                            ServiceTypeId = 2
                        },
                        new
                        {
                            TechnicianId = 3,
                            ServiceTypeId = 3
                        },
                        new
                        {
                            TechnicianId = 3,
                            ServiceTypeId = 4
                        },
                        new
                        {
                            TechnicianId = 3,
                            ServiceTypeId = 5
                        });
                });

            modelBuilder.Entity("UnifiedServiceScheduler.Data.Entities.Appointment", b =>
                {
                    b.HasOne("UnifiedServiceScheduler.Data.Entities.ServiceBay", "ServiceBay")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceBayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnifiedServiceScheduler.Data.Entities.ServiceType", "ServiceType")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnifiedServiceScheduler.Data.Entities.Technician", "Technician")
                        .WithMany("Appointments")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceBay");

                    b.Navigation("ServiceType");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("UnifiedServiceScheduler.Data.Entities.TechnicianQualification", b =>
                {
                    b.HasOne("UnifiedServiceScheduler.Data.Entities.ServiceType", "ServiceType")
                        .WithMany("TechnicianQualifications")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UnifiedServiceScheduler.Data.Entities.Technician", "Technician")
                        .WithMany("Qualifications")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceType");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("UnifiedServiceScheduler.Data.Entities.ServiceBay", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("UnifiedServiceScheduler.Data.Entities.ServiceType", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("TechnicianQualifications");
                });

            modelBuilder.Entity("UnifiedServiceScheduler.Data.Entities.Technician", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Qualifications");
                });
#pragma warning restore 612, 618
        }
    }
}
